In [ ]:
!apt-get update
!apt-get install g++ openjdk-8-jdk
!pip3 install konlpy
!pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0+cu113 torchtext==0.6.0 -f https://download.pytorch.org/whl/torch_stable.html

In [ ]:
import urllib.request
import pandas as pd

In [ ]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_train.txt",
                           filename="ratings_train.txt")
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_test.txt",
                           filename="ratings_test.txt")

('ratings_test.txt', <http.client.HTTPMessage at 0x7a76279860b0>)

In [ ]:
train_df = pd.read_table('ratings_train.txt')
test_df = pd.read_table('ratings_test.txt')

In [ ]:
train_df.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [ ]:
train_df['label'].value_counts()

label
0    75173
1    74827
Name: count, dtype: int64

In [ ]:
print('훈련 데이터 샘플의 개수 : {}'.format(len(train_df)))
print('테스트 데이터 샘플의 개수 : {}'.format(len(test_df)))

훈련 데이터 샘플의 개수 : 150000
테스트 데이터 샘플의 개수 : 50000

In [ ]:
from torchtext import data # torchtext.data 임포트
from konlpy.tag import Okt

In [ ]:
# Okt 토크나이저로 사용
tokenizer = Okt()

In [ ]:
ID = data.Field(sequential = False,
                use_vocab = False) # 실제 사용은 하지 않을 예정

TEXT = data.Field(batch_first = True,
                  fix_length = 30,
                  tokenize=tokenizer.morphs,  # tokenize = Okt()로 한국어 사용 가능
                  pad_token='<pad>',
                  unk_token='<unk>',
                  pad_first=True)

LABEL = data.Field(sequential=False,
                   use_vocab=False,
                   is_target=True)

In [ ]:
from torchtext.data import TabularDataset

In [ ]:
train_data, test_data = TabularDataset.splits(
        path='.', train='ratings_train.txt', test='ratings_test.txt', format='tsv',
        fields=[('id', ID), ('text', TEXT), ('label', LABEL)], skip_header=True)

In [ ]:
print('훈련 샘플의 개수 : {}'.format(len(train_data)))
print('테스트 샘플의 개수 : {}'.format(len(test_data)))

훈련 샘플의 개수 : 150000
테스트 샘플의 개수 : 50000

In [ ]:
print(vars(train_data[0]))

{'id': '9976970', 'text': ['아', '더빙', '..', '진짜', '짜증나네요', '목소리'], 'label': '0'}

In [ ]:
TEXT.build_vocab(train_data, min_freq=10, max_size=10000)
# min_freq : 단어 집합에 추가 시 단어의 최소 등장 빈도 조건을 추가.
# max_size : 단어 집합의 최대 크기를 지정.

In [ ]:
vocab_size = len(TEXT.vocab)
# Vocabulary Info
print(f'Vocab Size : {vocab_size}')

print('Vocab Examples : ')
for idx, (k, v) in enumerate(TEXT.vocab.stoi.items()):
    # stoi로 단어와 각 단어의 정수 인덱스가 저장되어져 있는 딕셔너리 객체에 접근
    if idx >= 10:
        break
    print('\t', k, v)
print('---------------------------------')

Vocab Size : 10002
Vocab Examples :
	 <unk> 0
	 <pad> 1
	 . 2
	 이 3
	 영화 4
	 의 5
	 .. 6
	 가 7
	 에 8
	 을 9
---------------------------------

In [ ]:
print('단어 집합의 크기 : {}'.format(len(TEXT.vocab)))

단어 집합의 크기 : 10002

In [ ]:
print(TEXT.vocab.stoi)

defaultdict(<bound method Vocab._default_unk_index of <torchtext.vocab.Vocab object at 0x7a752eca5a50>>, {'<unk>': 0, '<pad>': 1, '.': 2, '이': 3, '영화': 4, '의': 5, '..': 6, '가': 7, '에': 8, '을': 9, '...': 10, '도': 11, '들': 12, ',': 13, '는': 14, '를': 15, '은': 16, '너무': 17, '?': 18, '한': 19, '다': 20, '정말': 21, '적': 22, '만': 23, '!': 24, '진짜': 25, '으로': 26, '점': 27, '로': 28, '에서': 29, '연기': 30, '과': 31, '평점': 32, '것': 33, '최고': 34, '내': 35, '~': 36, '나': 37, '그': 38, '잘': 39, '와': 40, '안': 41, '인': 42, '이런': 43, '스토리': 44, '생각': 45, '못': 46, '....': 47, '왜': 48, '드라마': 49, '게': 50, '이다': 51, '감동': 52, '사람': 53, '1': 54, '하는': 55, '보고': 56, '하고': 57, '말': 58, '고': 59, '아': 60, '더': 61, '때': 62, 'ㅋㅋ': 63, '배우': 64, '거': 65, '감독': 66, '그냥': 67, '요': 68, '본': 69, '재미': 70, '내용': 71, '뭐': 72, '중': 73, '까지': 74, '!!': 75, '좀': 76, '쓰레기': 77, '보다': 78, '없는': 79, '시간': 80, '수': 81, '지': 82, '네': 83, '봤는데': 84, '10': 85, '작품': 86, '사랑': 87, '할': 88, '없다': 89, '다시': 90, '하나': 91, '볼': 92, '마지막': 93, '이건': 94, 'ㅋ': 95, '좋은': 96, '저': 97, '정도': 98, '입니다': 99, '같은': 100, '완전': 101, '있는': 102, '2': 103, 'ㅋㅋㅋ': 104, '처음': 105, '장면': 106, '액션': 107, '주인공': 108, '대': 109, '걸': 110, '이렇게': 111, '보는': 112, '개': 113, 'ㅠㅠ': 114, '최악': 115, '3': 116, "'": 117, '지금': 118, '돈': 119, '이야기': 120, '별로': 121, '임': 122, '참': 123, '하': 124, '봐도': 125, '느낌': 126, '연출': 127, '없고': 128, '라': 129, '끝': 130, '명작': 131, '듯': 132, '인데': 133, '별': 134, '그리고': 135, '역시': 136, '기': 137, '난': 138, '많이': 139, '서': 140, '재밌게': 141, '이해': 142, '^^': 143, '!!!': 144, 'ㅡㅡ': 145, '이영화': 146, '면': 147, '라고': 148, '보면': 149, '또': 150, '이나': 151, '여자': 152, '때문': 153, '성': 154, '부터': 155, '전': 156, '해서': 157, '아깝다': 158, '꼭': 159, '편': 160, '된': 161, '이고': 162, '보기': 163, '두': 164, '일': 165, '에게': 166, '여': 167, '짱': 168, '무슨': 169, '기억': 170, '엔': 171, '같다': 172, '결말': 173, '야': 174, 'ㅎㅎ': 175, '랑': 176, '마음': 177, '인생': 178, '소재': 179, 'ㅠ': 180, '~~': 181, '넘': 182, '애': 183, '님': 184, '없이': 185, '수준': 186, '영': 187, '현실': 188, '한다': 189, '해': 190, '씨': 191, '한번': 192, '속': 193, '가장': 194, '반전': 195, '급': 196, '제': 197, '함': 198, '매력': 199, '라는': 200, '전개': 201, ';;': 202, '??': 203, '남자': 204, '한국': 205, '뿐': 206, '가슴': 207, '되는': 208, '하지만': 209, '하게': 210, '알': 211, '음악': 212, '아이': 213, '다른': 214, '니': 215, '원작': 216, '만든': 217, '줄': 218, '인간': 219, '냐': 220, '우리': 221, '추천': 222, '눈물': 223, '않고': 224, '봤다': 225, '합니다': 226, '인지': 227, '모든': 228, '화': 229, '지만': 230, '번': 231, '자체': 232, '하지': 233, '눈': 234, '인가': 235, '캐릭터': 236, '코미디': 237, '솔직히': 238, '좋다': 239, 'ㅋㅋㅋㅋ': 240, '대박': 241, '처럼': 242, '움': 243, '뭔가': 244, '했다': 245, '대한': 246, '모두': 247, '이상': 248, '전혀': 249, '연기력': 250, '여운': 251, '이네': 252, '그래도': 253, '굿': 254, '기대': 255, '있다': 256, '개봉': 257, '근데': 258, '공감': 259, '일본': 260, '아주': 261, '허': 262, '중간': 263, '영상': 264, '표현': 265, ')': 266, '(': 267, '부분': 268, '시리즈': 269, '모습': 270, '자': 271, '그런': 272, '계속': 273, '에는': 274, '이라': 275, '제목': 276, '분': 277, '이랑': 278, '-': 279, '재밌다': 280, 'ㅎ': 281, '작': 282, '가족': 283, '내내': 284, ';': 285, 'OO': 286, '보지': 287, '후': 288, '하면': 289, '뭔': 290, '재미있게': 291, '진심': 292, '없음': 293, '실망': 294, '많은': 295, '봐': 296, '몰입': 297, '건지': 298, '어떻게': 299, '밖에': 300, '기분': 301, '나오는': 302, '였다': 303, '했는데': 304, 'ㅜㅜ': 305, '작가': 306, '봤습니다': 307, '위': 308, '아니다': 309, '이제': 310, '""': 311, '건': 312, '재미없다': 313, '보면서': 314, '않은': 315, ',,': 316, '잼': 317, '공포': 318, '요즘': 319, '용': 320, '아니고': 321, '감': 322, '스릴러': 323, '아니라': 324, '이라는': 325, '점도': 326, '4': 327, '개인': 328, '긴장감': 329, 'ㅡ': 330, '대사': 331, '않는': 332, '조금': 333, '하다': 334, '애니': 335, '이유': 336, '보다가': 337, '삶': 338, '알바': 339, '제대로': 340, '아닌': 341, '특히': 342, '아까운': 343, '노래': 344, '극장': 345, '욕': 346, '딱': 347, '한테': 348, '노잼': 349, '점수': 350, '시작': 351, '0': 352, '막장': 353, '아름다운': 354, '연': 355, '재밌어요': 356, '오랜': 357, '나름': 358, '이란': 359, '.....': 360, '시': 361, '이지': 362, '극': 363, '제일': 364, '차라리': 365, '놈': 366, '좋고': 367, '친구': 368, '에도': 369, '당시': 370, '같이': 371, '보게': 372, '영화로': 373, '봤어요': 374, '류': 375, '절대': 376, '의미': 377, '보세요': 378, '있고': 379, '만드는': 380, '세상': 381, '위해': 382, '력': 383, '식': 384, '싶다': 385, '몇': 386, '♥': 387, '뻔한': 388, '아직도': 389, '"': 390, '이라고': 391, '도대체': 392, '미국': 393, '명': 394, '해도': 395, '너': 396, '앞': 397, '공포영화': 398, '걍': 399, '오': 400, '보니': 401, '웃음': 402, '설정': 403, '무엇': 404, '마다': 405, '7': 406, '나도': 407, '아무': 408, '수작': 409, '물': 410, '주고': 411, '어': 412, '봄': 413, '뭘': 414, '데': 415, '우리나라': 416, '좋아하는': 417, '남': 418, '좋았다': 419, '초반': 420, '출연': 421, 'OOO': 422, '추억': 423, '사실': 424, '세': 425, '5': 426, '엄청': 427, '남는': 428, '보는내내': 429, '장난': 430, '안되는': 431, '준다': 432, '지루함': 433, '이야': 434, '한국영': 435, '가지': 436, '시나리오': 437, '주는': 438, '된다': 439, '분위기': 440, '팬': 441, '관객': 442, '시대': 443, '좋아요': 444, '지루하고': 445, '반': 446, '든': 447, '살': 448, '졸작': 449, '자신': 450, '이딴': 451, '소리': 452, '감정': 453, '같아요': 454, '봤던': 455, '접': 456, '최고다': 457, '오늘': 458, '이지만': 459, '영화관': 460, '엄마': 461, '엔딩': 462, '결국': 463, '주': 464, '정신': 465, '제발': 466, '인상': 467, '준': 468, '더빙': 469, '문제': 470, '캐스팅': 471, '포스터': 472, '라면': 473, '음': 474, '구': 475, '평가': 476, '코믹': 477, '~~~': 478, '어떤': 479, '니까': 480, '아무리': 481, '얼마나': 482, '될': 483, '엉': 484, '그저': 485, '신': 486, '애니메이션': 487, '함께': 488, '멋진': 489, '!!!!': 490, '몰입도': 491, '괜찮은': 492, '봐서': 493, '킬링타임': 494, '강추': 495, '배경': 496, '어릴': 497, '티비': 498, '했던': 499, '재밌음': 500, '뒤': 501, '8': 502, '대해': 503, '첨': 504, '맘': 505, '같은데': 506, '스릴': 507, '충격': 508, '개연': 509, '만화': 510, '질': 511, '건가': 512, '전쟁': 513, '그렇게': 514, '아니': 515, '책': 516, '머리': 517, '얘기': 518, '구성': 519, 'ㅜ': 520, '예술': 521, '갈수록': 522, '매우': 523, '머': 524, '보단': 525, '싶은': 526, '얼굴': 527, '까': 528, '웃기': 529, '하면서': 530, '후회': 531, '울': 532, '이름': 533, '재밌는': 534, '큰': 535, '기도': 536, '9': 537, '너무나': 538, '어디': 539, '옛날': 540, '나온': 541, '영화인': 542, '집중': 543, '않는다': 544, '이후': 545, '장르': 546, '조': 547, '꽤': 548, '봐라': 549, '지루한': 550, '집': 551, '총': 552, '주연': 553, '하는데': 554, '날': 555, '만들어': 556, '그래서': 557, '억지': 558, '간': 559, '원': 560, '모르겠다': 561, '존나': 562, '지루하다': 563, '진': 564, '???': 565, '누구': 566, '다큐': 567, '상황': 568, '비': 569, '재미없음': 570, '이리': 571, '+': 572, '글': 573, ',,,': 574, '씬': 575, '짜증': 576, '시즌': 577, '언제': 578, '아직': 579, '보는데': 580, '예전': 581, '다운': 582, '역사': 583, '후반': 584, '먹': 585, 'B': 586, '어느': 587, '걸작': 588, '아님': 589, '누가': 590, '마세요': 591, '여기': 592, '본다': 593, '약간': 594, '자기': 595, '실화': 596, '상': 597, '했지만': 598, '소름': 599, '그것': 600, '그나마': 601, '분들': 602, '인물': 603, '발연기': 604, '등': 605, '그대로': 606, '훨씬': 607, '방송': 608, '봤음': 609, '시절': 610, '~!': 611, '않다': 612, '부': 613, '아까': 614, '없어': 615, '보': 616, '비디오': 617, '할수': 618, '만점': 619, '휴': 620, '동안': 621, '판': 622, '한마디': 623, '간만': 624, '다음': 625, '대체': 626, '아들': 627, '재밌고': 628, 'CG': 629, '됨': 630, '사회': 631, '소설': 632, '로맨스': 633, '비교': 634, '초딩': 635, '봤지만': 636, '하기': 637, '6': 638, '이었다': 639, '감성': 640, '네이버': 641, '꿈': 642, '나와서': 643, '여배우': 644, '전체': 645, '여주': 646, '해야': 647, '없네': 648, '죠': 649, '라도': 650, '좋은데': 651, '같음': 652, '코': 653, '나이': 654, '성룡': 655, ';;;': 656, '나라': 657, '이라도': 658, '편이': 659, '만큼': 660, '였습니다': 661, '재': 662, '없었다': 663, '어렸을': 664, '삼류': 665, '재미있어요': 666, '혼자': 667, '순간': 668, '아쉽다': 669, '없어서': 670, '열': 671, '교훈': 672, '년': 673, '보다는': 674, 'ㅉㅉ': 675, '빨리': 676, '가는': 677, '그만': 678, '존재': 679, '하네요': 680, '힘': 681, '미친': 682, '바로': 683, '어설픈': 684, '주제': 685, '낸': 686, '......': 687, '목소리': 688, '에요': 689, '낭비': 690, '진정한': 691, '장': 692, '재밋': 693, '죽': 694, '거의': 695, '굳': 696, '당신': 697, '쯤': 698, '말고': 699, '몇번': 700, '안보': 701, '질질': 702, '는데': 703, '짜리': 704, '잔잔한': 705, '라니': 706, '재미있다': 707, '줄거리': 708, '상당히': 709, '딸': 710, '있지만': 711, '판타지': 712, '갑자기': 713, '되고': 714, '좋아': 715, '아버지': 716, '이번': 717, '점주': 718, '좀비': 719, '에선': 720, '그러나': 721, '보여주는': 722, '피': 723, '의도': 724, '전부': 725, '되어': 726, '모': 727, '어른': 728, '재밌네요': 729, '상영': 730, '하며': 731, 'ㅎㅎㅎ': 732, '실제': 733, '각본': 734, '소': 735, '시청률': 736, '믿고': 737, '있을까': 738, '제작': 739, '만하': 740, '으로도': 741, '난다': 742, '맛': 743, '평론가': 744, '곳': 745, '단': 746, '당': 747, '봤네요': 748, '바': 749, '버린': 750, '답': 751, '땜': 752, '한편': 753, '화면': 754, '필요': 755, '하네': 756, '비해': 757, '재미있는': 758, '그녀': 759, '히': 760, '같네요': 761, '극장판': 762, '나온다': 763, '사': 764, '쳐': 765, '/': 766, '간다': 767, '란': 768, '막': 769, '10년': 770, '중국': 771, '평': 772, '대로': 773, '되지': 774, '이하': 775, '있어서': 776, '볼때': 777, '세계': 778, '있는데': 779, '굉장히': 780, '밑': 781, '에서도': 782, '형': 783, '가치': 784, '그런지': 785, '선': 786, '훌륭한': 787, '관람': 788, '발': 789, '일단': 790, '좋네요': 791, '똥': 792, '스타일': 793, '있어': 794, '저런': 795, '선택': 796, '참고': 797, '복수': 798, '성우': 799, '터': 800, '뻔': 801, '요소': 802, '항상': 803, 'TV': 804, '둘': 805, '올': 806, '에서는': 807, '봐야': 808, '어디서': 809, '첫': 810, '햇': 811, '역': 812, '온': 813, '흥행': 814, '그때': 815, '어린': 816, '없네요': 817, '해주는': 818, '거기': 819, '모르고': 820, '더욱': 821, '여러': 822, '래': 823, '이냐': 824, '좋음': 825, '진행': 826, '치고': 827, '라서': 828, '슬픈': 829, '점점': 830, '물론': 831, '보는게': 832, '또한': 833, '였음': 834, '수가': 835, '아빠': 836, '역대': 837, '편집': 838, '어이': 839, '완성': 840, '인거': 841, '전형': 842, '멜로': 843, '재미없는': 844, '초': 845, '했음': 846, '새': 847, '화이팅': 848, 'ㅋㅋㅋㅋㅋ': 849, '상미': 850, '더럽게': 851, '술': 852, '이에요': 853, '충분히': 854, 'ㅠㅠㅠ': 855, '드': 856, '짓': 857, '해준': 858, 'tv': 859, '새로운': 860, '씩': 861, '불륜': 862, '에겐': 863, '개그': 864, '거지': 865, '귀': 866, '군': 867, '알았는데': 868, '잠': 869, '엉망': 870, '예상': 871, '미화': 872, '사건': 873, '낫다': 874, '병맛': 875, '중반': 876, '~!!': 877, '그게': 878, '꿀잼': 879, '무': 880, '설명': 881, '어쩔': 882, '나옴': 883, '과거': 884, '일이': 885, '있음': 886, '키': 887, '만에': 888, '배': 889, '좋겠다': 890, '프랑스': 891, '따': 892, '재밌는데': 893, '나오고': 894, '-_-': 895, '나올': 896, '도저히': 897, '손': 898, '흥미진진': 899, '노력': 900, '원래': 901, '그래픽': 902, '깊은': 903, '댓글': 904, '리': 905, '죽음': 906, '척': 907, '티': 908, '무조건': 909, '미': 910, '흥미': 911, '거리': 912, '몸': 913, '였어요': 914, '취향': 915, '않음': 916, '알았다': 917, '여서': 918, '하는게': 919, '현': 920, '안된다': 921, '있게': 922, '한다는': 923, 'good': 924, '따뜻한': 925, '자극': 926, '화가': 927, '감상': 928, '같아': 929, '대단한': 930, '만으로도': 931, '화보': 932, '새끼': 933, '아닌가': 934, '관': 935, '암': 936, '학교': 937, '아까워': 938, '예': 939, 'ost': 940, '괜히': 941, '흠': 942, '같습니다': 943, '자꾸': 944, '20': 945, ':': 946, '예고편': 947, '오히려': 948, '액션영화': 949, '좋았어요': 950, '결혼': 951, '며': 952, '바보': 953, '속편': 954, '심리': 955, '억': 956, '아저씨': 957, '엄청난': 958, '헐': 959, '게임': 960, '재밌었다': 961, '♡': 962, '이래': 963, '잘만': 964, '기대하고': 965, '만이': 966, '법': 967, '안됨': 968, '연기자': 969, '있을': 970, '마무리': 971, '맨': 972, '보이': 973, '관계': 974, '천재': 975, '땐': 976, '야할': 977, '이라니': 978, 'ㄷㄷ': 979, '귀신': 980, '양': 981, '억지로': 982, '표정': 983, 'SF': 984, '가서': 985, '되': 986, '봤을': 987, '전설': 988, '하하': 989, '느끼게': 990, '영환': 991, '최근': 992, '하는지': 993, '현재': 994, '높은': 995, '상상': 996, '유치': 997, '꺼': 998, '나쁜': 999, '산': 1000, '전편': 1001, '젠': 1002, '지루': 1003, '짐': 1004, '드는': 1005, '순': 1006, '대작': 1007, '아쉬움': 1008, '오래': 1009, '촬영': 1010, '따라': 1011, '오빠': 1012, '완벽한': 1013, '그닥': 1014, '다가': 1015, '대한민국': 1016, '타임': 1017, '하는거': 1018, '길': 1019, '재미있고': 1020, '조차': 1021, '우연히': 1022, '타': 1023, '만의': 1024, '재미없고': 1025, '회': 1026, '90년': 1027, '마': 1028, '메세지': 1029, '묘사': 1030, '스타': 1031, '엇': 1032, '존': 1033, '철학': 1034, 'ㅇ': 1035, '그렇고': 1036, '동화': 1037, '일까': 1038, '있었다': 1039, '프로그램': 1040, '그림': 1041, '2시간': 1042, '동': 1043, '살다': 1044, '조연': 1045, '프로': 1046, '예요': 1047, '쓴': 1048, '유치한': 1049, '이미': 1050, '전달': 1051, '>': 1052, '서로': 1053, '역할': 1054, '유머': 1055, '짜': 1056, '경찰': 1057, '그런데': 1058, '나중': 1059, '등장': 1060, '소녀': 1061, '아니면': 1062, '전작': 1063, '먼저': 1064, '무비': 1065, '스러운': 1066, '졸라': 1067, '지루하지': 1068, '다행': 1069, '모르는': 1070, '볼수': 1071, '정': 1072, '노': 1073, '마치': 1074, '망작': 1075, '받아': 1076, '봣': 1077, '재미없어': 1078, '했으면': 1079, '다만': 1080, '먹고': 1081, '살인': 1082, '공': 1083, '놔': 1084, '되었다': 1085, '아쉬운': 1086, '유치하고': 1087, '주의': 1088, '특유': 1089, '하냐': 1090, '100': 1091, '런가': 1092, '보이는': 1093, '이며': 1094, '힘든': 1095, '관심': 1096, '비슷한': 1097, '재밌었어요': 1098, '통해': 1099, '행동': 1100, '환상': 1101, '미래': 1102, '아니지만': 1103, '아닐까': 1104, '않았다': 1105, '인정': 1106, '맞는': 1107, '바람': 1108, '이면': 1109, '입': 1110, '노출': 1111, '비추': 1112, '사이': 1113, '같아서': 1114, '만들지': 1115, '안되고': 1116, '예산': 1117, '으': 1118, '지루해': 1119, '청춘': 1120, '해요': 1121, '군대': 1122, '리메이크': 1123, '왕': 1124, 'D': 1125, '깊이': 1126, '희망': 1127, '감사합니다': 1128, '보고싶다': 1129, '보시길': 1130, '생': 1131, '안나': 1132, '재밌어': 1133, '지난': 1134, '80년': 1135, 'ㅅㅂ': 1136, '께': 1137, '반개': 1138, '왠지': 1139, '좋았음': 1140, '필요없다': 1141, '느낄': 1142, '돼': 1143, '보고나서': 1144, '재미있음': 1145, '제작비': 1146, '봤으면': 1147, '생애': 1148, '영웅': 1149, '좋았습니다': 1150, '효과': 1151, '.......': 1152, 'OST': 1153, '긴': 1154, '아닌데': 1155, '외': 1156, '있나': 1157, '좋았고': 1158, '진부한': 1159, '손발': 1160, '용도': 1161, '화려한': 1162, '과정': 1163, '얼': 1164, '너무나도': 1165, '대의': 1166, '만들': 1167, '시도': 1168, '싫다': 1169, '이상한': 1170, '케이블': 1171, '평생': 1172, '범인': 1173, '봤었는데': 1174, '엿': 1175, '이런거': 1176, '채널': 1177, '강': 1178, '만들었다': 1179, '형님': 1180, '나왔으면': 1181, '능력': 1182, '버렸다': 1183, '빼고': 1184, '이런게': 1185, '가끔': 1186, '대단하다': 1187, '미소': 1188, '상상력': 1189, '스케일': 1190, '좋았는데': 1191, '결론': 1192, '그리': 1193, '기세': 1194, '였는데': 1195, '카메라': 1196, '다소': 1197, '체': 1198, 'cg': 1199, '광고': 1200, '낚': 1201, '낮은': 1202, '독립영화': 1203, '없을': 1204, '의리': 1205, '저렇게': 1206, '^': 1207, '그래': 1208, '대안': 1209, '대충': 1210, '드립니다': 1211, '않게': 1212, '잘못': 1213, '차': 1214, '확실히': 1215, '나와': 1216, '메시지': 1217, '언니': 1218, '자막': 1219, 'ㅇㅇ': 1220, '계': 1221, '보고싶은': 1222, '부족': 1223, '약': 1224, '없나': 1225, '있다면': 1226, '한계': 1227, '고민': 1228, '나를': 1229, '든다': 1230, '부족한': 1231, '여성': 1232, '고생': 1233, '되게': 1234, '슬프다': 1235, '슬픔': 1236, '어이없는': 1237, '"""': 1238, '메디': 1239, '봤다가': 1240, '으로는': 1241, '<': 1242, '않아': 1243, '귀여운': 1244, '들어': 1245, '마라': 1246, '볼수록': 1247, '없지만': 1248, '유쾌한': 1249, '있다는': 1250, '커플': 1251, '할까': 1252, '동생': 1253, '리얼': 1254, '매': 1255, '무서운': 1256, '밤': 1257, '방': 1258, '아는': 1259, '우': 1260, '유': 1261, '짱짱': 1262, '해라': 1263, '리뷰': 1264, '박수': 1265, '줌': 1266, '깊게': 1267, '보시': 1268, '순수한': 1269, '아닌듯': 1270, '아침': 1271, '어린이': 1272, '어색한': 1273, '재밌었는데': 1274, '..?': 1275, '귀엽고': 1276, '끝나고': 1277, '시청자': 1278, '있네': 1279, '필요없는': 1280, '괴물': 1281, '그럼': 1282, '됩니다': 1283, '로맨틱': 1284, '웃김': 1285, '자연': 1286, '흐름': 1287, '게이': 1288, '굳이': 1289, '로는': 1290, '멋': 1291, '써': 1292, '용이': 1293, '폭력': 1294, '개도': 1295, '개판': 1296, '겁나': 1297, '범죄': 1298, '살짝': 1299, '치': 1300, '포장': 1301, '봅니다': 1302, '스럽다': 1303, '쓰래': 1304, '있었던': 1305, '표절': 1306, '같고': 1307, '남는다': 1308, '달': 1309, '랄': 1310, '만들어진': 1311, '발견': 1312, '사극': 1313, '연애': 1314, '열심히': 1315, '정말로': 1316, '지도': 1317, '진실': 1318, '몸매': 1319, '문화': 1320, '빨': 1321, '수도': 1322, '스': 1323, '악역': 1324, '않을': 1325, '어찌': 1326, '언': 1327, '여전히': 1328, '인기': 1329, '좋아서': 1330, '포기': 1331, '감탄': 1332, '덕분': 1333, '성인': 1334, '주기': 1335, '진정': 1336, '~~~~': 1337, '시선': 1338, '일상': 1339, '쩐다': 1340, '했을': 1341, '혹시': 1342, '과연': 1343, '독특한': 1344, '문': 1345, '심': 1346, '있지': 1347, '정서': 1348, '조폭': 1349, '지는': 1350, '는걸': 1351, '보여준': 1352, '사는': 1353, '재밌습니다': 1354, '잼있게': 1355, '퀄리티': 1356, '평범한': 1357, '표': 1358, '하다가': 1359, '10분': 1360, '들이': 1361, '떨어지는': 1362, '로서': 1363, '보지마': 1364, '우정': 1365, '끼리': 1366, '뜻': 1367, '병': 1368, '상처': 1369, '재미없네': 1370, '젤': 1371, '하루': 1372, '하세요': 1373, '남녀': 1374, '성도': 1375, '스럽게': 1376, '오락': 1377, '용서': 1378, '웃겨': 1379, '이연걸': 1380, '막판': 1381, '몰라도': 1382, '악': 1383, '와는': 1384, '하니': 1385, '홍콩': 1386, '20년': 1387, '않나': 1388, '이기': 1389, '정치': 1390, '코드': 1391, '30분': 1392, '=': 1393, '갈': 1394, '그럭저럭': 1395, '말로': 1396, '볼거리': 1397, '죄': 1398, '크게': 1399, '홍보': 1400, '느껴지는': 1401, '별루': 1402, '보라': 1403, '빛': 1404, '쉽게': 1405, '아름답고': 1406, '어제': 1407, '좋게': 1408, 'b': 1409, '국민': 1410, '노답': 1411, '느와르': 1412, '뮤지컬': 1413, '낮아서': 1414, '등장인물': 1415, '보긴': 1416, '북한': 1417, '삼': 1418, '섹스': 1419, '않': 1420, '해피엔딩': 1421, '핵': 1422, '가진': 1423, '끌': 1424, '보아': 1425, '신선한': 1426, '없지': 1427, '으론': 1428, '팔': 1429, '펑펑': 1430, '힐링': 1431, '감명': 1432, '나머지': 1433, '무협': 1434, '반성': 1435, '아름답다': 1436, '아오': 1437, '에서의': 1438, '희생': 1439, '나서': 1440, '눈빛': 1441, '먼': 1442, '버리고': 1443, '불가': 1444, '재미있네요': 1445, '지루해서': 1446, '형편': 1447, '~^^': 1448, '다큐멘터리': 1449, '되네요': 1450, '받은': 1451, '자식': 1452, '자유': 1453, '좋습니다': 1454, '하여': 1455, '하자': 1456, '권': 1457, '남편': 1458, '많다': 1459, '본방': 1460, '쓰': 1461, '아깝지': 1462, '있어요': 1463, '짜증나는': 1464, '춤': 1465, '공부': 1466, '기술': 1467, '받고': 1468, '보다도': 1469, '불': 1470, '소장': 1471, '실감': 1472, '암튼': 1473, '올해': 1474, '했습니다': 1475, '그다지': 1476, '뜬금': 1477, '만든다': 1478, '죽는줄': 1479, '행복': 1480, '가면': 1481, '대화': 1482, '만으로': 1483, '싸움': 1484, '없는데': 1485, '열정': 1486, '쫌': 1487, '풀어': 1488, '(?)': 1489, '_': 1490, '고전': 1491, '기본': 1492, '까지는': 1493, '높다': 1494, '만들고': 1495, '에만': 1496, '차이': 1497, '하려는': 1498, '걸까': 1499, '까진': 1500, '누나': 1501, '늘': 1502, '라지': 1503, '무시': 1504, '비극': 1505, '비주': 1506, '슬프고': 1507, '오는': 1508, '의문': 1509, '입장': 1510, '있습니다': 1511, '제로': 1512, '그걸': 1513, '보인다': 1514, '불구': 1515, '싸구려': 1516, '않지만': 1517, '재밌었음': 1518, '종교': 1519, '했어요': 1520, '&': 1521, '가볍게': 1522, '기적': 1523, '긴장': 1524, '둘다': 1525, '디즈니': 1526, '마저': 1527, '빼고는': 1528, '으리': 1529, '이라서': 1530, '지구': 1531, 'ㅠㅠㅠㅠ': 1532, '게다가': 1533, '따위': 1534, '모르게': 1535, '시사회': 1536, '악당': 1537, '에게는': 1538, '있네요': 1539, '결과': 1540, '까지도': 1541, '받아서': 1542, '발전': 1543, '보러': 1544, '뻔하고': 1545, '실력': 1546, '아픔': 1547, '언제나': 1548, '좀더': 1549, '호러': 1550, '대가': 1551, '동물': 1552, '드럽게': 1553, '딱히': 1554, '무섭지도': 1555, '아줌마': 1556, '즈': 1557, '흑': 1558, '과는': 1559, '글쎄': 1560, '반복': 1561, '아이돌': 1562, '이쁘고': 1563, '이제야': 1564, '보길': 1565, '이니': 1566, '하다니': 1567, '단지': 1568, '러닝': 1569, '많고': 1570, '밥': 1571, '방금': 1572, '본인': 1573, '봐요': 1574, '서야': 1575, '아픈': 1576, '잊혀지지': 1577, '그린': 1578, '나오면': 1579, '백': 1580, '아름다': 1581, '재미없어요': 1582, '재밌네': 1583, '존경': 1584, '찍은': 1585, '창': 1586, '토': 1587, '분노': 1588, '여행': 1589, '예쁜': 1590, '전문가': 1591, '좋았던': 1592, '꼴': 1593, '넘치는': 1594, '맨날': 1595, '에로': 1596, '웃긴': 1597, '한다고': 1598, '할말이': 1599, '해석': 1600, '과의': 1601, '라인': 1602, '로봇': 1603, '선생님': 1604, '쓰고': 1605, '연예인': 1606, '외국': 1607, '있으면': 1608, '젊은': 1609, '평이': 1610, '그거': 1611, '실패': 1612, '어머니': 1613, '와우': 1614, '진리': 1615, '청소년': 1616, '누군가': 1617, '무언가': 1618, '벌써': 1619, '보지마라': 1620, '본게': 1621, '새벽': 1622, '짝': 1623, '한국인': 1624, '헐리우드': 1625, '견자단': 1626, '그렇다고': 1627, '대표': 1628, '돌려': 1629, '되서': 1630, '사랑스러운': 1631, '쇼': 1632, '오버': 1633, '외모': 1634, '질리': 1635, 'ㅋㅋㅋㅋㅋㅋ': 1636, '달라': 1637, '만족': 1638, '무섭다': 1639, '방법': 1640, '보고나면': 1641, '없어요': 1642, '좋': 1643, '좋아하는데': 1644, '주기도': 1645, '쩝': 1646, '필름': 1647, '갑니다': 1648, '금': 1649, '냥': 1650, '방식': 1651, '베스트': 1652, '생각나는': 1653, '성한': 1654, '시트콤': 1655, '이든': 1656, '재미있었다': 1657, '짝퉁': 1658, '최': 1659, '굿굿': 1660, '내고': 1661, '멋지다': 1662, '미드': 1663, '봣는데': 1664, '이었습니다': 1665, '좋아해서': 1666, '1시간': 1667, '갈등': 1668, '과장': 1669, '김기덕': 1670, '로만': 1671, '비판': 1672, '스스로': 1673, '애기': 1674, '연속': 1675, '이미지': 1676, '자리': 1677, '전개도': 1678, '죄다': 1679, '분명': 1680, '세기': 1681, '은근': 1682, '이쁘다': 1683, '이여': 1684, '이자': 1685, '쵝오': 1686, '팀': 1687, '히어로': 1688, '12': 1689, '떠나서': 1690, '뛰어난': 1691, '심장': 1692, '푹': 1693, '헐리웃': 1694, '...?': 1695, '가고': 1696, '국내': 1697, '딴': 1698, '명품': 1699, '모르겠고': 1700, '받는': 1701, '부모': 1702, '인가요': 1703, '재미있었어요': 1704, '조절': 1705, '30': 1706, '담': 1707, '맥': 1708, '시각': 1709, '싶네요': 1710, '작은': 1711, '단순한': 1712, '도전': 1713, '따뜻해지는': 1714, '미모': 1715, '이정': 1716, '주말': 1717, '즐겁게': 1718, '한데': 1719, '했는지': 1720, '극치': 1721, '두고': 1722, '레전드': 1723, '아쉽네요': 1724, '잔잔하고': 1725, '재밋다': 1726, '좋겠어요': 1727, '편의': 1728, '학생': 1729, '확': 1730, '희':

In [ ]:
import re
import sys
import random

import torch
import torch.nn as nn
import torch.nn.functional as F

from torchtext import data, datasets

In [ ]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [ ]:
from torchtext.data import Iterator

batch_size = 32
train_loader = Iterator(dataset=train_data, batch_size = batch_size, device=device)
test_loader = Iterator(dataset=test_data, batch_size = batch_size, device=device)

In [ ]:
print('훈련 데이터의 미니 배치 수 : {}'.format(len(train_loader)))
print('테스트 데이터의 미니 배치 수 : {}'.format(len(test_loader)))

훈련 데이터의 미니 배치 수 : 4688
테스트 데이터의 미니 배치 수 : 1563

In [ ]:
hidden_dim = 128
vocab_size = len(TEXT.vocab)
embed_dim = 300
n_classes = 1
n_layers = 1

In [ ]:
class LSTM(nn.Module):
    def __init__(self,n_layers, hidden_dim, vocab_size, embed_dim, n_classes, dropout_p=0.2):
        super().__init__()
        self.emb = nn.Embedding(num_embeddings = vocab_size, embedding_dim = embed_dim)
        self.LSTM = nn.LSTM (input_size = embed_dim,
                           hidden_size = hidden_dim,
                           num_layers = n_layers,
                           dropout = dropout_p,
                           batch_first = True) #
        self.drop = nn.Dropout(dropout_p)
        self.fc = nn.Linear(hidden_dim, n_classes)

    def forward(self, x):
        emb = self.emb(x)
        # emb : (Batch_Size, Max_Seq_Length, Emb_dim)
        output, hidden = self.LSTM(emb)
        last_output = output[:,-1,:]# (배치 크기, 은닉 상태의 크기)의 텐서로 크기가 변경됨. 즉, 마지막 time-step의 은닉 상태만 가져온다.
        x = self.fc(self.drop(last_output))

        return x

In [ ]:
loss_fn = nn.BCEWithLogitsLoss().to(device)

def binary_accuracy(preds, y):
    rounded_preds = torch.round(torch.sigmoid(preds))
    correct = (rounded_preds == y).float()
    acc = correct.sum()/len(correct)
    return acc

In [ ]:
LSTM_model = LSTM(n_layers, hidden_dim, vocab_size, embed_dim, n_classes).to(device)
optimizer = torch.optim.Adam(LSTM_model.parameters(), lr=0.001)

In [ ]:
def train(model, iterator, optimizer, loss_fn, idx_epoch, batch_size):

    epoch_loss = 0
    epoch_acc = 0

    model.train()
    batch_size = batch_size

    for idx, batch in enumerate(iterator):

        # Initializing
        optimizer.zero_grad()
        label = batch.label.float()
        # Forward
        predictions = model(batch.text).squeeze()
        loss = loss_fn(predictions, label)
        acc = binary_accuracy(predictions,label)

        sys.stdout.write(
                    "\r" + f"[Train] Epoch : {idx_epoch:^3}"\
                    f"[{(idx + 1) * batch_size} / {len(iterator) * batch_size} ({100. * (idx + 1) / len(iterator) :.4}%)]"\
                    f"  Loss: {loss.item():.4}"\
                    f"  Acc : {acc.item():.4}"\
                    )

        # Backward
        loss.backward()
        optimizer.step()

        # Update Epoch Performance
        epoch_loss += loss.item()
        epoch_acc += acc.item()

    return epoch_loss/len(iterator) , epoch_acc/len(iterator)

In [ ]:
def evaluate(model, iterator, loss_fn):

    epoch_loss = 0
    epoch_acc = 0

    # evaluation mode
    model.eval()
    with torch.no_grad():
        for batch in iterator:
            label = batch.label.float()
            predictions = model(batch.text).squeeze(1)
            loss = loss_fn(predictions, label)
            acc = binary_accuracy(predictions, label)

            epoch_loss += loss.item()
            epoch_acc += acc.item()

    return epoch_loss / len(iterator), epoch_acc / len(iterator)

In [ ]:
N_EPOCH = 5

best_valid_loss = float('inf')

for epoch in range(N_EPOCH):
    train_loss, train_acc = train(LSTM_model, train_loader, optimizer, loss_fn, epoch, batch_size)
    valid_loss, valid_acc = evaluate(LSTM_model, test_loader, loss_fn)
    print('')
    if valid_loss < best_valid_loss:
        best_valid_loss = valid_loss
        torch.save(LSTM_model.state_dict(), f'./LSTM_best_kor.pt')
        print(f'\t Saved at {epoch}-epoch')

    print(f'\t Epoch : {epoch} | Train Loss : {train_loss:.4} | Train Acc : {train_acc:.4}')
    print(f'\t Epoch : {epoch} | Valid Loss : {valid_loss:.4} | Valid Acc : {valid_acc:.4}')

[Train] Epoch :  0 [150016 / 150016 (100.0%)]  Loss: 0.1339  Acc : 0.9375
	 Saved at 0-epoch
	 Epoch : 0 | Train Loss : 0.3982 | Train Acc : 0.8138
	 Epoch : 0 | Valid Loss : 0.3519 | Valid Acc : 0.8427
[Train] Epoch :  1 [150016 / 150016 (100.0%)]  Loss: 0.1633  Acc : 0.9375
	 Saved at 1-epoch
	 Epoch : 1 | Train Loss : 0.2963 | Train Acc : 0.8712
	 Epoch : 1 | Valid Loss : 0.3396 | Valid Acc : 0.8482
[Train] Epoch :  2 [150016 / 150016 (100.0%)]  Loss: 0.1187  Acc : 1.0
	 Epoch : 2 | Train Loss : 0.2418 | Train Acc : 0.8984
	 Epoch : 2 | Valid Loss : 0.3525 | Valid Acc : 0.848
[Train] Epoch :  3 [150016 / 150016 (100.0%)]  Loss: 0.05512  Acc : 1.0
	 Epoch : 3 | Train Loss : 0.1948 | Train Acc : 0.9196
	 Epoch : 3 | Valid Loss : 0.3854 | Valid Acc : 0.8478
[Train] Epoch :  4 [150016 / 150016 (100.0%)]  Loss: 0.09123  Acc : 1.0
	 Epoch : 4 | Train Loss : 0.1531 | Train Acc : 0.938
	 Epoch : 4 | Valid Loss : 0.4209 | Valid Acc : 0.8446